### ISSUE TITLE
Update README.md with example of how to integrate with express-gateway after installation step

### ISSUE THREAD

**Issue by pthieu** [ExpressGateway/express-gateway-plugin-example#4]
I have a specific situation where I want to provide express-gateway with a custom route that is resolved and served from the express-gateway, a basic ping-pong health check.

I followed the plugin steps and installed this plugin and am not sure how to configure the gateway to be able to hit `hello-eg`.

**Comment by XVincentX** [comment]
Hey,
I'm sorry for the late reply, I wasn't subscribed to this repository.

This can be done through a [plugin route](https://www.express-gateway.io/docs/plugins/route-development/)
