### ISSUE TITLE
manifest.js not installed

### ISSUE THREAD

**Issue by farshidbakh** [ExpressGateway/express-gateway-plugin-example#5]
Hello,

Thanks for this example. 

I followed your instructions and issued:

eg plugin install example
? Would you like to enable this plugin in system config? Yes
? Would you like to add new policies to gateway config? Yes
Plugin installed!

Note: I got only two of the questions instead of four that you have on your page. 
I didn't get the manifest.js file, instead I have server.js file. Do I need to download your code separately and make manifest.js as "main" ins the system.config.yml file?  

Please let me know.  I am just starting to learn Express Gateway. I would appreciate your response. 

Thanks,
Farshid

**Comment by farshidbakh** [comment]
I am using Express Gateway version 1.9.1.

**Comment by XVincentX** [comment]
Hey,

I think you're confusing two parts.

The `server.js` file is the one produced by the scaffolding command (`eg gateway create`).

The `manifest.js` file is just an arbitrary name you export as a module to create an Express Gateway plugin. It can be any name, as long you export it correctly and declare its presence to the `package.json`

Does that clarify the thing a little bit?
